### ISSUE TITLE
Odd floating & crashing behavior

### ISSUE THREAD

**Issue by Shadowdragon019** [appsinacup/godot-box2d#88]
**Describe the bug**
Player is floating above solid ground
![image](https://github.com/appsinacup/godot-box2d/assets/67480398/324dbb9a-06a1-46e7-9d18-0bb46c56a18f)
Attempting to launch a hook makes the game freeze, then crash without error. But I somehow had it not happen twice on two different project runs, but I can't replicate that.

**To Reproduce**
1. Download the attached project
2. See the floating behavior
3. Left-click to launch a projectile, the project will freeze then crash

**Expected behavior**
I expect for no floating & for the projectile to be spawned as intended
Video example: https://github.com/appsinacup/godot-box2d/assets/67480398/46370d38-7237-4597-ae07-1c7fdb109f22

**Project**
[Woods.zip](https://github.com/appsinacup/godot-box2d/files/13631649/Woods.zip)

**Versions (please complete the following information):**
 - OS: Windows
 - Godot 4.2
 - Box2d 0.9.6

**Comment by Ughuuu** [comment]
Floating seems to be because of polygon skin. With box2c that won't be an issue. I will investigate the crash though.

**Comment by Ughuuu** [comment]
There is not trace or anything as I am exporting the add-on in release mode for all cases, so that it runs fast. As such, if there is a crash, I have to compile it manually in debug mode(if you want you can also compile it in debug mode, but only use case for that is if there is an error in the code or a crash).
